app_default:
    resource: '@AppBundle/Resources/config/routing/default.yml'
    prefix: /
app_post:
    resource: '@AppBundle/Resources/config/routing/post.yml'
    prefix: /post
app_blog:
    resource: '@AppBundle/Resources/config/routing/blog.yml'
    prefix: /blog