AppBundle\Entity\Post:
    type: entity
    table: posts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        createdat:
            type: date
            nullable: false
        blogId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: blog_id
    lifecycleCallbacks: {  }
